import { useState } from 'react';
import { ArrowLeft, BarChart3, Bell, CheckCircle2, ChevronRight, Download, Eye, FileText, Lock, Mail, ShieldCheck, Table2, UsersRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import './BusinessDeliveryPreview.css';

const exampleBreakdown = [
  { label: '选项 A', count: 48, percent: 48, tone: 'blue' }, { label: '选项 B', count: 28, percent: 28, tone: 'violet' }, { label: '选项 C', count: 16, percent: 16, tone: 'mint' }, { label: '其他', count: 8, percent: 8, tone: 'sand' },
];
const workflow = [['01', '答卷归集', '仅纳入通过质量检查的答卷'], ['02', '研究报告', '管理员整理发现、方法与附件'], ['03', '交付版本', '确认可见范围并生成冻结版本'], ['04', '消息通知', '客户收到消息后在此查看交付物']];

function LockedSurface({ title, body, icon: Icon = Lock }) { return <section className="delivery-locked-surface"><span><Icon size={20} /></span><div><h3>{title}</h3><p>{body}</p></div><Lock size={17} /></section>; }

function RecipientPreview({ locked }) {
  if (locked) return <section className="delivery-recipient-layout delivery-is-locked"><div className="delivery-locked-head"><span><Lock size={18} /> 结果区已锁定</span><h2>尚未收到可交付的研究报告</h2><p>调查尚无已确认的结果，或管理员尚未向你发送交付版本。答卷、报告和下载内容会在交付后同时开放。</p></div><div className="delivery-locked-grid"><LockedSurface title="执行概览" body="样本、完成率和质量说明将在交付版本中显示。" icon={UsersRound} /><LockedSurface title="问题结果" body="问题级图表和分群比较仅在发布后可见。" icon={BarChart3} /><LockedSurface title="研究报告" body="管理员确认的摘要、发现和附件将固定为一个版本。" icon={FileText} /><LockedSurface title="答卷明细" body="默认不开放逐份答卷；如有授权，会在报告中说明。" icon={Table2} /></div></section>;
  return <section className="delivery-recipient-layout"><div className="delivery-delivered-banner"><div><span><CheckCircle2 size={16} /> 交付版本 · 界面示例</span><h2>研究结果已准备好</h2><p>以下为布局与信息层级的展示样例；不是本项目的真实数据、发现或结论。</p></div><button type="button"><Download size={16} /> 下载报告 <small>示例</small></button></div><div className="delivery-stats-grid"><article><small>有效答卷</small><strong>—</strong><p>真实答卷接入后显示</p></article><article><small>交付版本</small><strong>v1.0</strong><p>发布后冻结，不随草稿改变</p></article><article><small>研究状态</small><strong>已交付</strong><p>这是状态与排版示例</p></article><article><small>查看权限</small><strong>仅项目成员</strong><p>由管理员交付时确认</p></article></div><div className="delivery-main-grid"><section className="delivery-results-card"><header><div><p>问题结果 · 界面示例</p><h2>示例问题：请从下列选项中选择最符合的一项</h2><span>图表会随管理员交付的答卷快照固定。</span></div><button type="button">问题 1 <ChevronRight size={15} /></button></header><div className="delivery-chart-layout"><div className="delivery-bars">{exampleBreakdown.map((row) => <div key={row.label}><div><span>{row.label}</span><b>{row.percent}%</b></div><i><em className={`tone-${row.tone}`} style={{ width: `${row.percent}%` }} /></i><small>{row.count} 份 <span>（示例）</span></small></div>)}</div><div className="delivery-donut-wrap"><div className="delivery-donut"><span>100<small>样例占比</small></span></div><ul>{exampleBreakdown.map((row) => <li key={row.label}><i className={`tone-${row.tone}`} />{row.label}</li>)}</ul></div></div></section><aside className="delivery-report-card"><header><div><p>研究报告</p><h2>交付内容</h2></div><FileText size={19} /></header><ol><li><CheckCircle2 size={15} /><span><b>执行摘要</b><small>研究目的、范围与阅读说明</small></span></li><li><CheckCircle2 size={15} /><span><b>关键发现</b><small>仅由管理员确认后写入</small></span></li><li><CheckCircle2 size={15} /><span><b>方法与样本</b><small>样本口径、时间与质量说明</small></span></li><li><CheckCircle2 size={15} /><span><b>附录与附件</b><small>按交付许可提供下载</small></span></li></ol><button type="button">打开报告阅读器 <ChevronRight size={15} /></button></aside></div><section className="delivery-records-card"><header><div><p>答卷记录</p><h2>明细表结构</h2><span>默认仅展示经授权的字段；下表仅用于预览排版。</span></div><button type="button"><Table2 size={15} /> 字段与权限</button></header><div className="delivery-records-table"><div className="delivery-records-row delivery-records-label"><span>记录</span><span>完成时间</span><span>问题 1</span><span>质量状态</span></div>{[1, 2, 3].map((item) => <div className="delivery-records-row delivery-records-skeleton" key={item}><span>—</span><span /><span /><span><i /> 待交付</span></div>)}</div></section></section>;
}

function AdminPreview() { return <section className="delivery-admin-preview"><div className="delivery-admin-intro"><span><ShieldCheck size={17} /> 管理员交付流程 · 界面示例</span><h2>把已审核的报告作为一个版本发送</h2><p>系统不会自动生成结论或发送给用户。管理员须先确认研究报告、可见字段和附件，再执行交付。</p></div><div className="delivery-admin-grid"><section><header><span>01</span><div><p>报告编辑</p><h3>编写可交付版本</h3></div></header><ul><li>执行摘要、发现、方法与限制</li><li>问题图表与分群比较</li><li>附件、下载文件与访问期限</li></ul><button type="button"><FileText size={15} /> 打开报告编辑器 <small>预览</small></button></section><section><header><span>02</span><div><p>可见范围</p><h3>确认交付内容</h3></div></header><ul><li>默认不给客户开放原始答卷</li><li>敏感字段、开放题与附件逐项确认</li><li>发布后生成不可更改的版本快照</li></ul><button type="button"><Eye size={15} /> 查看客户视图 <small>预览</small></button></section><section><header><span>03</span><div><p>发送与留痕</p><h3>通知项目成员</h3></div></header><ul><li>交付后更新客户结果区状态</li><li>向项目消息栏发送一则交付通知</li><li>记录发送人、时间和版本号</li></ul><button type="button" className="delivery-send-example"><Mail size={15} /> 发送交付通知 <small>预览</small></button></section></div><section className="delivery-message-preview"><Bell size={19} /><div><p>客户消息 · 示例</p><strong>你的《项目研究报告》已准备好</strong><span>管理员已向你交付版本 v1.0。你可以在“结果与报告”中查看阅读版与获授权的下载文件。</span></div><CheckCircle2 size={18} /></section></section>; }

export default function BusinessDeliveryPreview() { const [audience, setAudience] = useState('recipient'); const [locked, setLocked] = useState(false); return <main className="delivery-preview-page"><header className="delivery-preview-header"><Link to="/business/workspace?view=results"><img src="/guanyisearch-brand-mark-transparent.png" alt="GuanyiSearch" /><ArrowLeft size={17} /> 返回结果区</Link><div><span>仅供设计检阅</span><button type="button" className={audience === 'recipient' ? 'is-active' : ''} onClick={() => setAudience('recipient')}>客户交付页</button><button type="button" className={audience === 'admin' ? 'is-active' : ''} onClick={() => setAudience('admin')}>管理员交付流</button></div></header><section className="delivery-preview-hero"><div><p>RESULT DELIVERY CENTRE</p><h1>研究报告与结果交付</h1><span>这是前端界面预览。它不连接答卷数据、不会生成结论，也不会发送任何消息。</span></div><div className="delivery-state-switch">{audience === 'recipient' && <><button type="button" className={!locked ? 'is-active' : ''} onClick={() => setLocked(false)}><Eye size={15} /> 查看交付态</button><button type="button" className={locked ? 'is-active' : ''} onClick={() => setLocked(true)}><Lock size={15} /> 查看锁定态</button></>}</div></section><section className="delivery-workflow"><header><div><p>交付逻辑</p><h2>先审核，再交付；交付后客户可见</h2></div><span>不会自动发布</span></header><div>{workflow.map(([number, title, body]) => <article key={number}><em>{number}</em><div><strong>{title}</strong><small>{body}</small></div></article>)}</div></section>{audience === 'recipient' ? <RecipientPreview locked={locked} /> : <AdminPreview />}</main>; }
