import { useEffect, useMemo, useState } from 'react';
import { Archive, ArrowLeft, ArrowRight, Check, ClipboardList, Copy, Eye, LoaderCircle, Plus, SlidersHorizontal, Trash2 } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { archiveBusinessQuestionnaire, duplicateBusinessQuestionnaire, getBusinessProject, getBusinessQuestionnaireResponses, publishBusinessQuestionnaire, saveBusinessQuestionnaire } from '../api/realApi';
import './BusinessQuestionnaire.css';

const questionTypes = [
  ['SINGLE_CHOICE', 'Single choice'], ['MULTIPLE_CHOICE', 'Multiple choice'], ['RANKING', 'Rank choices'],
  ['RATING', 'Rating scale'], ['NUMBER', 'Number'], ['SHORT_TEXT', 'Short text'], ['LONG_TEXT', 'Long text'],
];
const questionSections = [['SCREENING', 'Screening'], ['CORE', 'Core questions'], ['PROFILE', 'Profile'], ['CLOSING', 'Closing']];
const collectionOptions = [
  ['SELF_DISTRIBUTED', 'Share it yourself', 'Create a link for your own customers, members, or contacts.'],
  ['AUDIENCE_SOURCING', 'Source respondents', 'Request a tailored audience and response plan from GuanyiSearch.'],
  ['RESEARCH_SUPPORT', 'Research support', 'Request questionnaire design support or a tailored study proposal.'],
];
const choiceQuestion = (type) => ['SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'RATING', 'RANKING'].includes(type);
const logicSourceQuestion = (type) => ['SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'RATING'].includes(type);
const defaultChoices = (type) => type === 'RATING' ? ['1', '2', '3', '4', '5'] : choiceQuestion(type) ? ['Option 1', 'Option 2'] : [];
const defaultSettings = () => ({ allowOther: false, maxSelections: null, randomizeChoices: false, scaleLowLabel: '', scaleHighLabel: '' });
const questionKey = () => window.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const newQuestion = (type = 'SINGLE_CHOICE') => ({ tempId: questionKey(), type, section: 'CORE', prompt: '', required: false, choices: defaultChoices(type), settings: defaultSettings(), logic: null });
const normalizeQuestion = (question) => ({ ...newQuestion(question.type || 'SINGLE_CHOICE'), ...question, section: question.section || 'CORE', choices: Array.isArray(question.choices) ? question.choices : defaultChoices(question.type), settings: { ...defaultSettings(), ...(question.settings || {}) }, logic: question.logic || null });

function QuestionCard({ question, index, questions, locked, onUpdate, onRemove }) {
  const isChoice = choiceQuestion(question.type);
  const sources = questions.slice(0, index).filter((item) => logicSourceQuestion(item.type) && item.choices?.length);
  const logicSource = sources.find((item) => item.position + 1 === question.logic?.sourcePosition || questions.indexOf(item) + 1 === question.logic?.sourcePosition);
  const sourceChoices = logicSource?.choices || [];
  const settings = { ...defaultSettings(), ...(question.settings || {}) };
  const updateSettings = (changes) => onUpdate({ settings: { ...settings, ...changes } });
  const changeType = (type) => onUpdate({ type, choices: choiceQuestion(type) ? (question.type === type && question.choices?.length ? question.choices : defaultChoices(type)) : [], settings: { ...settings, allowOther: ['SINGLE_CHOICE', 'MULTIPLE_CHOICE'].includes(type) ? settings.allowOther : false, maxSelections: type === 'MULTIPLE_CHOICE' ? settings.maxSelections : null } });
  const updateChoice = (choiceIndex, value) => onUpdate({ choices: question.choices.map((choice, position) => position === choiceIndex ? value : choice) });
  return <article className="business-question-card business-question-card-rich">
    <div className="business-question-card-head"><span>Question {index + 1}</span><div><select aria-label={`Question ${index + 1} section`} value={question.section} disabled={locked} onChange={(event) => onUpdate({ section: event.target.value })}>{questionSections.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><button type="button" disabled={locked} onClick={onRemove} aria-label={`Delete question ${index + 1}`}><Trash2 size={16} /></button></div></div>
    <textarea value={question.prompt} disabled={locked} onChange={(event) => onUpdate({ prompt: event.target.value })} placeholder="Write a clear, single-focus question" aria-label={`Question ${index + 1} text`} />
    <div className="business-question-controls"><select value={question.type} disabled={locked} onChange={(event) => changeType(event.target.value)}>{questionTypes.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><label><input type="checkbox" disabled={locked} checked={question.required} onChange={(event) => onUpdate({ required: event.target.checked })} /> Required</label></div>
    {isChoice && <div className="business-question-choices">{question.choices.map((choice, choiceIndex) => <div key={`${question.id || question.tempId}-${choiceIndex}`}><span>{choiceIndex + 1}</span><input value={choice} disabled={locked} onChange={(event) => updateChoice(choiceIndex, event.target.value)} aria-label={`Option ${choiceIndex + 1}`} /><button type="button" disabled={locked || question.choices.length <= 2} onClick={() => onUpdate({ choices: question.choices.filter((_, position) => position !== choiceIndex) })}><Trash2 size={15} /></button></div>)}<button className="business-question-add-choice" disabled={locked || question.type === 'RATING'} type="button" onClick={() => onUpdate({ choices: [...question.choices, `Option ${question.choices.length + 1}`] })}><Plus size={14} /> Add option</button></div>}
    <div className="business-question-advanced">
      {['SINGLE_CHOICE', 'MULTIPLE_CHOICE'].includes(question.type) && <label><input type="checkbox" disabled={locked} checked={settings.allowOther} onChange={(event) => updateSettings({ allowOther: event.target.checked })} /> Let people write another answer</label>}
      {isChoice && <label><input type="checkbox" disabled={locked} checked={settings.randomizeChoices} onChange={(event) => updateSettings({ randomizeChoices: event.target.checked })} /> Shuffle choices for respondents</label>}
      {question.type === 'MULTIPLE_CHOICE' && <label className="business-inline-number">Maximum selections <input type="number" min="1" max={Math.max(1, question.choices.length)} disabled={locked} value={settings.maxSelections || ''} onChange={(event) => updateSettings({ maxSelections: event.target.value ? Number(event.target.value) : null })} /></label>}
      {question.type === 'RATING' && <div className="business-scale-labels"><input value={settings.scaleLowLabel} disabled={locked} onChange={(event) => updateSettings({ scaleLowLabel: event.target.value })} placeholder="Low-end label (optional)" /><input value={settings.scaleHighLabel} disabled={locked} onChange={(event) => updateSettings({ scaleHighLabel: event.target.value })} placeholder="High-end label (optional)" /></div>}
    </div>
    {sources.length > 0 && <details className="business-question-logic"><summary><SlidersHorizontal size={14} /> Display rule {question.logic ? '· active' : ''}</summary><p>Show this question only when an earlier answer matches.</p><label><input type="checkbox" disabled={locked} checked={Boolean(question.logic)} onChange={(event) => onUpdate({ logic: event.target.checked ? { sourcePosition: questions.indexOf(sources[0]) + 1, value: sources[0].choices[0] } : null })} /> Use a display rule</label>{question.logic && <div><select disabled={locked} value={question.logic.sourcePosition} onChange={(event) => { const source = questions[Number(event.target.value) - 1]; onUpdate({ logic: { sourcePosition: Number(event.target.value), value: source?.choices?.[0] || '' } }); }}>{sources.map((source) => <option value={questions.indexOf(source) + 1} key={source.id || source.tempId}>Q{questions.indexOf(source) + 1}: {source.prompt || 'Untitled question'}</option>)}</select><select disabled={locked} value={question.logic.value} onChange={(event) => onUpdate({ logic: { ...question.logic, value: event.target.value } })}>{sourceChoices.map((choice) => <option value={choice} key={choice}>{choice}</option>)}</select></div>}</details>}
  </article>;
}

function buildChecks(questions) {
  const checks = [];
  const core = questions.filter((question) => question.section === 'CORE').length;
  const open = questions.filter((question) => ['SHORT_TEXT', 'LONG_TEXT'].includes(question.type)).length;
  if (!questions.length) checks.push(['warning', 'Add the first question to start a usable questionnaire.']);
  if (questions.length > 20) checks.push(['warning', 'This draft has more than 20 questions. Consider whether every question supports the decision.']);
  if (questions.length && !core) checks.push(['warning', 'Add at least one core question that answers the study goal.']);
  if (open > Math.ceil(Math.max(questions.length, 1) / 3)) checks.push(['warning', 'There are many open-text questions. They take longer to answer and analyse.']);
  questions.forEach((question, index) => {
    if (question.prompt.trim().length < 3) checks.push(['warning', `Question ${index + 1} needs clear wording.`]);
    if (choiceQuestion(question.type) && question.choices.filter(Boolean).length < 2) checks.push(['warning', `Question ${index + 1} needs at least two answer options.`]);
    if (question.logic && question.logic.sourcePosition >= index + 1) checks.push(['warning', `Question ${index + 1} has a display rule that must point to an earlier question.`]);
  });
  if (!checks.length) checks.push(['ready', 'Structure looks ready to preview. Review wording, audience and consent before publishing.']);
  return checks;
}

export default function BusinessQuestionnaireBuilder() {
  const { projectId } = useParams(); const navigate = useNavigate();
  const [project, setProject] = useState(null); const [title, setTitle] = useState(''); const [coverDescription, setCoverDescription] = useState(''); const [questions, setQuestions] = useState([]); const [collectionMode, setCollectionMode] = useState('SELF_DISTRIBUTED');
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [sensitiveNoticeOpen, setSensitiveNoticeOpen] = useState(false); const [responses, setResponses] = useState([]);
  const questionnaire = project?.questionnaire; const responseCount = questionnaire?.responseCount || 0; const structureLocked = questionnaire?.status === 'PUBLISHED' && responseCount > 0;
  const publicUrl = useMemo(() => questionnaire?.publicId ? `${window.location.origin}/business/s/${questionnaire.publicId}` : '', [questionnaire?.publicId]);
  const checks = useMemo(() => buildChecks(questions), [questions]);
  const statusLabel = questionnaire?.status === 'PENDING_REVIEW' ? (collectionMode === 'SELF_DISTRIBUTED' ? 'Pending publication review' : 'Quote requested · content review pending') : questionnaire?.status === 'APPROVED' ? 'Content approved · awaiting launch' : questionnaire?.status === 'PUBLISHED' ? (questionnaire.isCollecting ? 'Live' : 'Collection paused') : questionnaire?.status === 'ARCHIVED' ? 'Archived' : 'Draft';
  useEffect(() => { let active = true; getBusinessProject(projectId).then((response) => { if (!active) return; const nextProject = response.data.project; if (!nextProject.questionnaire) { navigate('/business/workspace', { replace: true }); return; } setProject(nextProject); setTitle(nextProject.questionnaire.title || nextProject.title); setCoverDescription(nextProject.questionnaire.coverDescription || ''); setCollectionMode(nextProject.questionnaire.collectionMode || 'SELF_DISTRIBUTED'); setQuestions((nextProject.questionnaire.questions || []).map(normalizeQuestion)); if (nextProject.questionnaire.responseCount) getBusinessQuestionnaireResponses(projectId).then((result) => { if (active) setResponses(result.data.responses || []); }).catch(() => {}); }).catch((caughtError) => { if (active) setError(caughtError.response?.data?.message || 'We could not load this questionnaire.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [navigate, projectId]);
  const updateQuestion = (index, changes) => { if (!structureLocked) setQuestions((current) => current.map((question, position) => position === index ? { ...question, ...changes } : question)); };
  const save = async ({ publish = false, sensitiveDataAcknowledged = false } = {}) => { if (!questionnaire || saving) return; setSaving(true); setMessage(''); setError(''); try { const response = await saveBusinessQuestionnaire(projectId, { title, coverDescription, collectionMode, isCollecting: questionnaire.status === 'PUBLISHED' ? questionnaire.isCollecting : false, questions: questions.map(({ type, section, prompt, required, choices, settings, logic }) => ({ type, section, prompt, required, choices, settings, logic })) }); let nextQuestionnaire = response.data.questionnaire; if (publish) nextQuestionnaire = (await publishBusinessQuestionnaire(projectId, { sensitiveDataAcknowledged })).data.questionnaire; setProject((current) => ({ ...current, questionnaire: nextQuestionnaire })); setQuestions((nextQuestionnaire.questions || questions).map(normalizeQuestion)); setSensitiveNoticeOpen(false); setMessage(publish ? (collectionMode === 'SELF_DISTRIBUTED' ? 'Your questionnaire is pending publication review.' : 'Your project is submitted for scope, pricing and content review.') : 'Draft saved.'); } catch (caughtError) { if (publish && caughtError.response?.data?.code === 'SENSITIVE_DATA_NOTICE_REQUIRED') setSensitiveNoticeOpen(true); setError(caughtError.response?.data?.message || 'We could not save this questionnaire. Please check the questions and try again.'); } finally { setSaving(false); } };
  const archive = async () => { if (!questionnaire || saving) return; setSaving(true); setError(''); try { const response = await archiveBusinessQuestionnaire(projectId); setProject((current) => ({ ...current, questionnaire: response.data.questionnaire })); setMessage('Questionnaire archived. Its public link is no longer collecting responses.'); } catch (caughtError) { setError(caughtError.response?.data?.message || 'We could not archive this questionnaire.'); } finally { setSaving(false); } };
  const duplicate = async () => { if (!questionnaire || saving) return; setSaving(true); setError(''); try { const response = await duplicateBusinessQuestionnaire(projectId); navigate(`/business/projects/${response.data.project.id}`); } catch (caughtError) { setError(caughtError.response?.data?.message || 'We could not copy this questionnaire.'); } finally { setSaving(false); } };
  const copyPublicLink = async () => { try { await window.navigator.clipboard.writeText(publicUrl); setMessage('Share link copied.'); } catch { setError('Copy was not available in this browser.'); } };
  if (loading) return <main className="business-builder-loading"><LoaderCircle className="animate-spin" /> Loading questionnaire</main>;
  if (error && !project) return <main className="business-builder-loading"><strong>{error}</strong><Link to="/business/workspace">Back to projects</Link></main>;
  return <main className="business-builder"><header className="business-builder-header"><Link to="/business/workspace"><ArrowLeft size={17} /> Projects</Link><div><span>{statusLabel}</span><button type="button" onClick={() => save()} disabled={saving}>{saving ? <LoaderCircle className="animate-spin" size={16} /> : 'Save draft'}</button>{['DRAFT', 'ARCHIVED'].includes(questionnaire.status) && <button className="business-builder-publish" type="button" onClick={() => save({ publish: true })} disabled={saving || !questions.length}>{saving ? <LoaderCircle className="animate-spin" size={16} /> : collectionMode === 'SELF_DISTRIBUTED' ? 'Submit for publication' : 'Request quote & review'} <ArrowRight size={16} /></button>}{['PUBLISHED', 'PENDING_REVIEW', 'APPROVED'].includes(questionnaire.status) && <button type="button" onClick={archive} disabled={saving}><Archive size={15} /> Archive</button>}</div></header>
    <div className="business-builder-layout"><section className="business-builder-main"><p className="business-eyebrow">QUESTIONNAIRE DESIGN</p><input className="business-builder-title" value={title} onChange={(event) => setTitle(event.target.value)} aria-label="Questionnaire title" placeholder="Questionnaire title" /><p className="business-builder-lede">Build a focused questionnaire: screen the right people, answer the core decision, then gather only the profile details you need.</p><label className="business-cover-field"><span>What will respondents know?</span><textarea value={coverDescription} onChange={(event) => setCoverDescription(event.target.value)} maxLength={600} placeholder="Explain the purpose of this questionnaire and how responses will be used." /></label>{structureLocked && <div className="business-builder-lock"><strong>This questionnaire already has responses.</strong><span>Question wording and structure are locked to protect the integrity of your data.</span><button type="button" onClick={duplicate} disabled={saving}>Copy as new questionnaire <ArrowRight size={15} /></button></div>}{message && <p className="business-builder-message is-success"><Check size={16} /> {message}</p>}{error && <p className="business-builder-message">{error}</p>}
      <div className="business-question-list">{questions.map((question, index) => <QuestionCard key={question.id || question.tempId} question={question} index={index} questions={questions} locked={structureLocked} onUpdate={(changes) => updateQuestion(index, changes)} onRemove={() => !structureLocked && setQuestions((current) => current.filter((_, position) => position !== index))} />)}</div>
      <div className="business-add-question"><ClipboardList size={20} /><div><strong>Add a question</strong><span>Use a question type that fits the answer you need.</span></div><div className="business-add-question-actions">{questionTypes.slice(0, 5).map(([type, label]) => <button type="button" disabled={structureLocked} onClick={() => setQuestions((current) => [...current, newQuestion(type)])} key={type}><Plus size={14} /> {label}</button>)}</div></div>
    </section><aside className="business-builder-sidebar"><section className="business-design-checks"><p>DESIGN CHECK</p><h2>Before you publish</h2>{checks.map(([state, text], index) => <div className={state} key={`${state}-${index}`}><span>{state === 'ready' ? <Check size={14} /> : '!'}</span>{text}</div>)}</section><section><p>RESPONSE COLLECTION</p><h2>How will you collect responses?</h2><div className="business-collection-options">{collectionOptions.map(([value, label, description]) => <label key={value} className={collectionMode === value ? 'is-selected' : ''}><input type="radio" name="collectionMode" disabled={structureLocked} value={value} checked={collectionMode === value} onChange={() => setCollectionMode(value)} /><strong>{label}</strong><span>{description}</span></label>)}</div>{collectionMode !== 'SELF_DISTRIBUTED' && <p className="business-collection-note">Submitting starts scope, pricing and content review. Recruitment does not begin until funding and launch are confirmed.</p>}</section><section className="business-share-card"><p>SHARE LINK</p>{questionnaire.status === 'PUBLISHED' && questionnaire.isCollecting ? <><strong>Ready to send</strong><span>{publicUrl}</span><button type="button" onClick={copyPublicLink}><Copy size={15} /> Copy link</button><a href={publicUrl} target="_blank" rel="noreferrer"><Eye size={15} /> Open questionnaire</a></> : <><strong>Save your draft, then submit when ready.</strong><span>You can keep editing until you request publication or research support.</span></>}</section><section className="business-response-card"><p>RESPONSES</p><strong>{responseCount}</strong><span>responses received</span></section></aside></div>
    {responses.length > 0 && <section className="business-response-list"><p>RESPONSE DATA</p><h2>Latest responses</h2>{responses.slice(0, 25).map((response) => <article key={response.id}><header><span>{new Date(response.submittedAt).toLocaleString()}</span>{response.qualityFlag && <em>Flagged: {response.qualityFlag === 'TOO_FAST' ? 'completed unusually quickly' : response.qualityFlag}</em>}</header>{questions.map((question) => response.answers[question.id] !== undefined && <div key={question.id}><strong>{question.prompt}</strong><span>{Array.isArray(response.answers[question.id]) ? response.answers[question.id].join(', ') : String(response.answers[question.id])}</span></div>)}</article>)}</section>}
    {sensitiveNoticeOpen && <div className="business-sensitive-modal" role="dialog" aria-modal="true"><div><p>SENSITIVE DATA NOTICE</p><h2>Confirm before requesting publication</h2><span>This questionnaire may ask about sensitive personal information. You must obtain any required consent and comply with the laws that apply to your research.</span><section><button type="button" onClick={() => setSensitiveNoticeOpen(false)}>Go back</button><button type="button" className="business-builder-publish" onClick={() => save({ publish: true, sensitiveDataAcknowledged: true })}>I understand and confirm</button></section></div></div>}
  </main>;
}
